Style/Documentation:
  Enabled: false
Layout/LineLength:
  Max: 100
Metrics/BlockLength:
  Max: 100
Style/FrozenStringLiteralComment:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true