language: ruby

services:
  - docker

before_install:
  - export CI_COMMIT=$(echo ${TRAVIS_COMMIT:0:8})
  - export DOCKER_REPO_HUB=mini-go-resto
  - "which ssh-agent || (sudo apt-get update -y && sudo apt-get install -y openssh-client)"
  - eval $(ssh-agent -s)
  - ssh-add <(echo $SSH_PRIVATE_KEY | base64 -d)
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

jobs:
  include:
    - stage: test
      script: ./deployment/travis-script/test.sh
    - stage: deploy
      script: ./deployment/travis-script/deploy.sh

stages:
  - test
  - deploy
