language: ruby

services:
  - docker

before_install:
  - export CI_COMMIT=$(echo ${TRAVIS_COMMIT:0:8})
  - export DOCKER_REPO_HUB=mini-go-resto
  - export ENTRYPOINT=up
  - export RAILS_ENV=development
  - docker-compose build
  - docker images
  - "which ssh-agent || (sudo apt-get update -y && sudo apt-get install -y openssh-client)"
  - eval $(ssh-agent -s)
  - ssh-add <(echo $SSH_PRIVATE_KEY | base64 -d)
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

install:
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
  - docker push $DOCKER_HUB_USERNAME/$DOCKER_REPO_HUB:$CI_COMMIT
  - ssh $DEPLOYMENT_HOST "docker pull $DOCKER_HUB_USERNAME/$DOCKER_REPO_HUB:$CI_COMMIT"
  - ssh $DEPLOYMENT_HOST "docker-compose run -d"
